name: 'load private action'
inputs:
  repository:  
    required: true
  ref:
    default: main
    required: true
  token:
    required: true
  action-name:
    required: true

runs:
  using: "composite"
  steps:
  - name: Get composite run steps repository
    uses: actions/checkout@v2
    with:
      repository: ${{ inputs.repositroy }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}
      path: .github/${{ inputs.action-name }}
  
  - name: Run action from private repo
    uses: ./.github/${{ inputs.action-name }}
