name: 'load private action'
inputs:
  repository:  
    required: true
  ref:
    default: main
    required: true
  token:
    required: 
    default: ${secrets.ADM_REPO_WRITE}
outputs:
  action-path:
    description: "Private action path"
    value: .github/${{ steps.random-path.outputs.random-id }}

runs:
  using: "composite"
  steps:
  - id: random-path
    run: echo "::set-output name=random-id::$(date +%s)"
    shell: bash
  
  - name: Get composite run steps repository
    uses: actions/checkout@v2
    with:
      repository: ${{ inputs.repositroy }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}
      path: .github/${{ steps.random-path.outputs.random-id }}
