name: 'load private action'
inputs:
  repository:  
    required: true
  ref:
    default: main
    required: true
  token:
    required: true
  action-name:
    required: true

runs:
  using: "composite"
  steps:
  - name: Get composite run steps repository
    uses: actions/checkout@v3
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}
      path: .github/${{ inputs.action-name }}
